// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCucln1Z06HD6df52wNMQxbXInSBozcIUI',
    appId: '1:758780034879:web:e2665f15a0593943c6dd8a',
    messagingSenderId: '758780034879',
    projectId: 'green-market-32046',
    authDomain: 'green-market-32046.firebaseapp.com',
    storageBucket: 'green-market-32046.firebasestorage.app',
    measurementId: 'G-39R7725GFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdChf_ndw0_-NfkUWV5oMQnK2jxhKd3PA',
    appId: '1:758780034879:android:8630060dd2417321c6dd8a',
    messagingSenderId: '758780034879',
    projectId: 'green-market-32046',
    storageBucket: 'green-market-32046.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0He6O4MC1h8OeMc4TrCSIM47S4OyO2Kg',
    appId: '1:758780034879:ios:fe6a2c1527c238afc6dd8a',
    messagingSenderId: '758780034879',
    projectId: 'green-market-32046',
    storageBucket: 'green-market-32046.firebasestorage.app',
    iosBundleId: 'com.example.greenMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0He6O4MC1h8OeMc4TrCSIM47S4OyO2Kg',
    appId: '1:758780034879:ios:fe6a2c1527c238afc6dd8a',
    messagingSenderId: '758780034879',
    projectId: 'green-market-32046',
    storageBucket: 'green-market-32046.firebasestorage.app',
    iosBundleId: 'com.example.greenMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCucln1Z06HD6df52wNMQxbXInSBozcIUI',
    appId: '1:758780034879:web:e7cea566eb1f953fc6dd8a',
    messagingSenderId: '758780034879',
    projectId: 'green-market-32046',
    authDomain: 'green-market-32046.firebaseapp.com',
    storageBucket: 'green-market-32046.firebasestorage.app',
    measurementId: 'G-NGC2J69QC1',
  );
}
